services:
  directory-service:
    container_name: directory-service
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seq-data:/data

volumes:
  seq-data:
